const fs = require('fs');
const path = require('path');
const moment = require('moment');

const CONFIG_FILE_PATH = path.resolve(__dirname + '/../database.json');

function requireUncached(module) {
    delete require.cache[require.resolve(module)];
    return require(module)
}

const environments = ['stage', 'development', 'production'];

const createDbConfig = environments.reduce((prev, environment) => {
    //change environment and require same file again
    process.env.NODE_CONF = environment;
    return {
        ...prev,
        [environment]: {
            ...requireUncached('../auth').MYSQL_CONFIG,
            driver: "mysql",
            multipleStatements: true // Required when executing multiple statements
        }
    }
}, {
    _info_: `Generated by dbconfig.js on ${moment().format('LLLL')}. DO NOT CHANGE MANUALLY!`,
    defaultEnv: {ENV: 'NODE_CONF'}
});

// Check if the file is writable.
fs.open(CONFIG_FILE_PATH, 'w', function (err, fd) {
    if (err) {
        return console.error('database.json is not writable');
    }

    fs.writeSync(fd, JSON.stringify(createDbConfig, null, 4));
    fs.close(fd, err => {
        if (err) {
            console.error('database.json could not be written');
        }
        console.log('database.json file written');
    });
});


